apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: facu077/fincasappuaa
      context: ../fincasApp-uaa
      jib: {}
  tagPolicy:
    envTemplate:
      template: '{{.IMAGE_NAME}}:latest'
deploy:
  kustomize: {}
